littlelemon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurant/urls.py
from django.urls import path
from . import views

app_name = 'restaurant'

urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('book/', views.book, name="book"),
    path('menu/', views.menu, name='menu'),
    path('menu/<int:pk>/', views.menu_item, name ='menu_item'),
]

restaurant/models.py
from django.db import models


# Create your models here.
class Booking(models.Model):
   first_name = models.CharField(max_length=200)    
   last_name = models.CharField(max_length=200)
   guest_number = models.IntegerField()
   comment = models.CharField(max_length=1000)

   def __str__(self):
      return self.first_name + ' ' + self.last_name


# generating unique file names for image uploads
def post_image_path(instance, filename):
    filename = os.path.basename(slugify(filename))  # remove any directory paths from filename
    return (f'img/{instance.id or 1}/{filename}')

class Menu(models.Model):
   name = models.CharField(max_length=200)
   description = models.TextField()
   image = models.ImageField(upload_to='post_image_path', blank=True)
   price = models.FloatField()

   class Meta:
      ordering = ('name',)

   def __str__(self):
      return str(self.title)
    
   def get_absolute_url(self):
      return reverse('restaurant:menu_item', kwargs={'pk': self.pk})
    

restaurant/forms.py
from django.forms import ModelForm
from .models import Booking


# Code added for loading form data on the Booking page
class BookingForm(ModelForm):
    class Meta:
        model = Booking
        fields = "__all__"

restaurant/views.py
from django.shortcuts import render, get_object_or_404
from .forms import BookingForm
from .models import Menu


def home(request):
    return render(request, 'restaurant/index.html')

def about(request):
    return render(request, 'restaurant/about.html')

def book(request):
    form = BookingForm()
    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            form.save()
    context = {'form':form}
    return render(request, 'restaurant/book.html', context)

def menu(request):
    menu_items = Menu.objects.all().order_by('name')
    context = {
        'menu' : menu_items
    }
    return render(request, 'restaurant/menu.html', context)

def menu_item(request, pk):
    menu_item = Menu.get_object_or_404(pk=pk)
    context = {
        'menu_item': menu_item,
    }
    return render(request, 'restaurant/menu-item.html', context)

restaurant/templates/restaurant/about.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}
<section>
  <article>
    <h1>About Us</h1>
    <!--Begin row-->
    <div class="row">
      <!--Begin col-->
      <div class="column">
        <p>
          Based in Chicago, Illinois, Little Lemon is a family owned
          Mediterranean restaurant, focused on traditional recipes served with a
          modern twist.
        </p>
        <p>
          The chefs draw inspiration from Italian, Greek, and Turkish culture
          and have a menu of 12-15 items that they rotate seasonally.
        </p>

        <p>
          The restaurant has a rustic and relaxed atmosphere with moderate
          prices, making it a popular place for a meal any time of the day.
        </p>

        <p>
          Little Lemon is owned by two Italian brothers, Mario and Adrian, who
          moved to the United States to pursue their shared dream of owning a
          restaurant.
        </p>

        <p>
          To craft the menu, Mario relies on family recipes and his experience
          as a chef in Italy.
        </p>

        <p>
          Adrian does all the marketing for the restaurant and led the effort to
          expand the menu beyond classic Italian to incorporate additional
          cuisines from the mediterranean region.
        </p>
      </div>
      <!--End col-->

      <!--Begin col-->
      <div class="column">
        <figure class="figure">
          <img
            src="{% static 'img/mario-and-adrian.jpg' %}"
            alt="Mario and Adrian"
          />
          <figcaption class="figure-caption">
            Little Lemon owners Mario and Adrian.
          </figcaption>
        </figure>
      </div>
      <!--End col-->
    </div>
    <!--End row-->
  </article>
</section>
{% endblock %}

restaurant/templates/restaurant/book.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section>
  <article>
    <h1>Make a reservation</h1>
    <!--Begin row-->
    <div class="row">
      <!--Begin col-->
      <div class="column">
        <form action="" method="post">
          {% csrf_token %}
          {{form.as_p}}
          <input type="submit" id="button">
        </form>
      </div>
      <!--End col-->

      <!--Begin col-->
      <div class="column">
        <div class="videowrap">
          <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11898.289517452584!2d-87.60853049433447!3d41.79442860243028!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x880e2912ce6f7027%3A0xc0cfb5545d4a37b2!2sHyde%20Park%2C%20Chicago%2C%20IL%2C%20USA!5e0!3m2!1sen!2spt!4v1662384760663!5m2!1sen!2spt"
            width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"
            referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
      </div>
      <!--End col-->
    </div>
    <!--End row-->




  </article>
</section>
{% endblock %}

restaurant/templates/restaurant/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section>
    <article id="hero">
      <h1 class="heading_shadow">SPECIAL OFFER</h1>
      <p>
        30% Off This Weekend 
      </p>
      <a href="#" class="cta"> Book now </a>
    </article>
  </section>
  <section>
    <article>
      <h2>Our New Menu</h2>
      <img src="{% static 'img/grill.jpg' %}">
      <p>
        Our menu consists of 12-15 seasonal items based on Italian, Greek, and Turkish culture.
      </p>
      <p>
        <a href="{% url 'restaurant:menu' %}">See our new menu</a>
      </p>
    </article>
    <article>
      <h2>Book a table</h2>
      <img src="{% static 'img/salad.jpg' %}">
      <p>
        Reserve your table for an Italian, Greek, and Turkish dining experience.
      </p>
      <p>
        <a href="{% url 'restaurant:book' %}">Book your table now</a>
      </p>
    </article>
    <article>
      <h2>Opening Hours</h2>
      <img src="{% static 'img/head_chef.jpg' %}">
      <p>
        The Little Lemon Restaurant is open 7 days a week, except for public holidays. 
      </p>
      <ul>
        <li>Mon - Fri: 2pm - 10pm</li>
        <li>Sat: 2pm - 11pm</li>
        <li>Sun: 2pm - 9pm</li>
      </ul>
    </article>
  </section>
{% endblock %}

restaurant/templates/restaurant/menu.html
{% extends 'base.html' %}
{% block content %}
<section>
    <h1>Menu</h1>
        <!--Begin row-->
        <div class="row">
            <!--Begin col-->
            <div class="column">
    
            </div>
            <!--End col-->
        </div>
</section>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>Little Lemon | {% block title %}{% endblock %}</title>
    <meta name="description" content="A brief description" />
    <meta name="author"
        content="Based in Chicago, Illinois, Little Lemon is a family owned Mediterranean restaurant, focused on traditional recipes served with a modern twist." />

    <!-- Load favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}" />

    <!-- Include your CSS files here -->
    <link rel="preload" as="style" href="{% static 'css/style.css' %}" onload="this.rel = 'stylesheet'" />

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Karla&family=Markazi+Text:wght@500&display=swap"
        rel="stylesheet" />
</head>

<body>
    <!--Header content-->
    {% include 'partials/_header.html' %}

    <main>{% block content %} {% endblock %}</main>

    <!--Footer content-->
    {% include 'partials/_footer.html' %}
</body>

</html>

templates/partials/_header.html
{% load static %}
<header>
  <img src="{% static 'img/logo.png' %}" />
</header>
<nav>
  <ul>
    <li><a href="{% url 'restaurant:home' %}">Home</a></li>
    <li><a href="{% url 'restaurant:about' %}">About</a></li>
    <li><a href="{% url 'restaurant:menu' %}">Menu</a></li>
    <li><a href="{% url 'restaurant:book' %}">Book</a></li>
  </ul>
</nav>